### ISSUE TITLE
NextStep and PrevStep in Schedular recovery

### ISSUE THREAD

**Issue by carsonal** [Cook-E-team/Cook-E#12]
NextStep and PrevStep do not recover when asking for prevstep if there is no prevstep or nextstep if there is no nextstep. Should be able to ask for prevstep if made a mistake and went past the last step.

**Comment by samcrow** [comment]
This looks like it might have been fixed.

**Comment by tsjacoby** [comment]
There is no way to go past the last step and no way to get the current step. If you're at the end of the steps and call for the next step then it returns null. Then if you call for the previous step it returns the second to last step if present. What behavior is desired?

**Comment by samcrow** [comment]
For the user interface, one convenient thing would be to have the getNextStep/getPreviousStep methods return a value that has some information about the status.

The returned value could contain the next step, or it could indicate that the user has reached the end of the recipe or that the scheduler is waiting for a parallel step to finish.

Alternatively, the user interface could call methods to get that information (isAtEnd and isWaitingForSimultaneousStep) after getNextStep/getPreviousStep.

Sam

**Comment by tsjacoby** [comment]
I've added a getCurrStep function and another one called isAtFinalStep. The Schedules interface isn't very fun to use, but hopefully this is enough to get us by.
