### ISSUE TITLE
SQLite code should close() Cursors

### ISSUE THREAD

**Issue by samcrow** [Cook-E-team/Cook-E#15]
All code that uses SQLite to retrieve data must explicitly close any cursors that it uses. Not doing so might cause memory or resource leaks.

Cursor closing can be ensured with try-finally blocks:

    final Cursor result = ...;
    try {
        get data from cursor
    } finally {
        cursor.close();
    }

The `SQLiteAccessor` class does not currently do this.

**Comment by kylewoo235** [comment]
fixed
