### ISSUE TITLE
mVisibleRecipes unexpectedly null

### ISSUE THREAD

**Issue by samcrow** [Cook-E-team/Cook-E#28]
The home activity sometimes "crashes" because mVisibleRecipes is null when it should not be.

Sam has not been able to reproduce the problem. More information is needed.

**Comment by tsjacoby** [comment]
This used to happen for me, but with the latest version from master it doesn't. At this time I only get a "java.sql.SQLException: java.text.ParseException: Invalid JSON" and it says "Failed to load recipes".

**Comment by samcrow** [comment]
The ParseException is probably a result of the recipe serialization format change associated with [issue 22](https://github.com/Cook-E-team/Cook-E/issues/22). The JSON parser cannot read recipe steps serialized in the previous format. Clearing the application data should fix that.

**Comment by tsjacoby** [comment]
That was exactly it. I cleared the data and it all works now. Thanks Sam!

**Comment by zijinzhang** [comment]
I used to have this problem, but it works now.

**Comment by samcrow** [comment]
It looks like everyone's problems have been resolved, so I am closing this issue.
