### ISSUE TITLE
Recipe images are not cleaned up when recipes are deleted

### ISSUE THREAD

**Issue by samcrow** [Cook-E-team/Cook-E#34]
The current technique for storing recipes calculates a file name from the CRC-32 checksum of the compressed image data and stores the image on the file system. However, there is no way to delete image files when recipes are deleted. This problem could eventually use up all the storage on a device.

The paths to images are stored in the recipe table, so finding and deleting image files that are not used by any recipes would be easy. Someone could set up an asynchronous task to do this regularly, maybe every time the home activity is created.

**Comment by kylewoo235** [comment]
We have changed how the file names are calculated such that they are guranteed not to be shared.
